### ISSUE TITLE
“Swap Used”

### ISSUE THREAD

**Issue by tjluoma** [richie5um/TextBar-Recipes#12]
Here's another one I've wanted for literally years and could never find, even with GeekTool or Menu Meters. If you look in Activity Monitor on the “Memory” tab, it will show “Swap Used” at the bottom. If this gets too high, especially with a spinning disk, your Mac can really slow down.

Now I can show it in the menu bar:

	top -S -n0 -l1 | awk -F' ' '/^Swap/{print $2}'

I only run that one about once every 10 minutes, because `top` is a fairly CPU intensive command, ironically enough.

(Credit: **darkuncle** on Twitter: <https://twitter.com/darkuncle/status/593513107940454400>)

**Comment by richie5um** [comment]
Nice. I’ve added it to my machine. I’ll update the recipes page.

Have you been using the new DefaultFont/Size preferences? I’m finding them invaluable (using a thiner and small font) as I add more things to my MenuBar - I’ve also evicted more things to my Bartender extended menu. :-)

Thanks.

-Rich
On 30 April 2015 at 14:33:50, TJ Luoma (notifications@github.com) wrote:

Here's another one I've wanted for literally years and could never find, even with GeekTool or Menu Meters. If you look in Activity Monitor on the “Memory” tab, it will show “Swap Used” at the bottom. If this gets too high, especially with a spinning disk, your Mac can really slow down.

Now I can show it in the menu bar:

top -S -n0 -l1 | awk -F' ' '/^Swap/{print $2}'

I only run that one about once every 10 minutes, because top is a fairly CPU intensive command, ironically enough.

(Credit: darkuncle on Twitter: https://twitter.com/darkuncle/status/593513107940454400)

**Comment by tjluoma** [comment]
I haven’t used the font sizes yet. Right now the only things I have on 
my menu bar are TextBar, smcFanControl, FruitJuice, and Mountain, so I 
haven’t needed the space yet.
