### ISSUE TITLE
No site/volume license available for purchase?

### ISSUE THREAD

**Issue by karanzazu** [richie5um/TextBar-Recipes#33]
Hi, I'd like to purchase TextBar for my organization but don't see an option on your site for volume purchase.  Am I required to purchase one license per computer?

Thanks!

**Comment by richie5um** [comment]
Hi,

I don't currently have a volume purchase mechanism, but, I'm sure we can sort something out.

How many licenses were you intending on buying?

Regards,
Rich

**Comment by karanzazu** [comment]
Hi Rich,

Thanks for getting back to me. I'm looking to purchase 100 licenses for now and possibly more in the near future. If we could work somethings out that would be great!

Thanks,

Kenny

**Comment by richie5um** [comment]
Hi Kenny,

I can happily offer you a 33% discount if you want to purchase 100+
licenses.

If this is acceptable, I can either generate you 100 individual licenses,
or, I can generate you a single license that you can use across all 100
machines.

It may be useful to email me directly if you want to continue this
conversation: rs@richsomerfield.com

Regards,
Rich



On 9 July 2016 at 18:20:59, karanzazu (notifications@github.com) wrote:

Hi Rich,

Thanks for getting back to me. I'm looking to purchase 100 licenses for now
and possibly more in the near future. If we could work somethings out that
would be great!

Thanks,

Kenny

> On Jul 9, 2016, at 12:12 PM, Rich Somerfield <notifications@github.com>
wrote:
>
> Hi,
>
> I don't currently have a volume purchase mechanism, but, I'm sure we can
sort something out.
>
> How many licenses were you intending on buying?
>
> Regards,
> Rich
>
> On 8 Jul 2016, 22:28 +0100, karanzazu<notifications@github.com>, wrote:
> >
> > Hi, I'd like to purchase TextBar for my organization but don't see an
option on your site for volume purchase. Am I required to purchase one
license per computer?
> >
> >
> > Thanks!
> >
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly,view it on GitHub(
https://github.com/richie5um/TextBar-Recipes/issues/33), ormute the thread(
https://github.com/notifications/unsubscribe/AA3XGc3XsE-Qs00MjuKe8_5nMGq0Q2rqks5qTsDqgaJpZM4JIaZF
).
> >
> >
> >
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/richie5um/TextBar-Recipes/issues/33#issuecomment-231545286>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA3XGXmoqT1T8EChD2poWVeC9ZoBv0A2ks5qT9h7gaJpZM4JIaZF>
.

**Comment by warthurton** [comment]
Recommend closing and moving to private email conversation.
